spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xth-prod?characterEncoding=utf8&useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  redis:
      database: 0 # Redis数据库索引（默认为0）
      host: localhost # Redis服务器地址
      port: 6379 # Redis服务器连接端口
      password:
      timeout: 0 # 连接超时时间（毫秒）
      pool:
          max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 100 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
logging:
  level:
    org:
      springframework:
        data: DEBUG
    sample:
      mybatis:
        mapper: TRACE
    com.xth.mapper: debug
redis:
    shiro:
        host: localhost
        port: 6379
        password:

file:
  wechat:
    upload:
      path: E:\Project\xingtihui\